# Gmail to SMS Automation Workflow
# Runs every 15 minutes to check for new emails and send SMS notifications
# 
# Required repository secrets:
# - GMAIL_CLIENT_ID: OAuth client ID from Google Cloud Console
# - GMAIL_CLIENT_SECRET: OAuth client secret from Google Cloud Console
# - GMAIL_REFRESH_TOKEN: OAuth refresh token for Gmail access
# - COHERE_API_KEY: API key for Cohere's AI services
# - TEXTBELT_API_KEY_NEW: API key for TextBelt SMS service
# - PHONE_NUMBER: Primary phone number to receive SMS
# - PHONE_NUMBER_2: (Optional) Secondary phone number
#
# For setup instructions, see: README.md

name: Check Emails

on:
  # Run every 15 minutes
  schedule:
    - cron: '*/15 * * * *'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  check-emails:
    runs-on: ubuntu-latest
    
    steps:
      # Check out repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'  # Enable npm caching for faster installs
          
      # Install project dependencies
      - name: Install dependencies
        run: |
          npm ci  # Faster, more reliable than npm install
          
      # Run the email checking script
      - name: Check for new emails
        env:
          # Gmail OAuth credentials
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          
          # API keys
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          TEXTBELT_API_KEY_NEW: ${{ secrets.TEXTBELT_API_KEY_NEW }}
          
          # Phone numbers for SMS
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          PHONE_NUMBER_2: ${{ secrets.PHONE_NUMBER_2 }}
        run: |
          echo "Starting email check..."
          node src/scripts/check-emails.js